### PR TITLE
Updated py-ransac to work in Python 3

### PR DESCRIPTION
**Pull request by luke-skywalker**
I made minor changes to get this to cleanly run in Python 3. I also replaced pylab with pyplot since pylab will drop support for Python 3 in 2020. Thank you for this piece of work!

### CODE REVIEW

**Comment by falcondai** [comment]
I am glad this piece of old code was of value to you. This is a great enhancement! Do you mind using `six` and `__future__` to support both python 2 and 3?

**Comment by luke-skywalker** [comment]
I was unclear in my comment, the way it is now runs both in python 2 *and* python 3 :)
To safely back up this statement I just:
+ freshly re-cloned the repo
+ created a virtual environment with python 2.7.12
+ `pip install`ed `numpy` and `matplotlib`
+ ...and everything runs smoothly!

Just let me know if I'm missing something though, I'd be more than glad to act accordingly!

**Comment by luke-skywalker** [comment]
(Sorry, I was furiously typing and I closed the pull request by mistake! Reopened it right away!)

**Comment by falcondai** [comment]
No worries at all. Sounds good. Merged. Thanks again for contributing!

**Pull request merged**
